services:
  backend:
    build: ./backend
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - portfolio-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge
